apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-webapp-dep
  labels:
    app: frontend-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-webapp
  template:
    metadata:
      labels:
        app: frontend-webapp
    spec:
      containers:
      - name: frontend-webapp-pod
        image: kamranshaikh111/cloudethix_configmap_kamran:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: "/usr/share/nginx/html/"
      volumes:
      - name: config-volume
        configMap:
          name: config-task
