apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp-dep
  labels:
    app: flask-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-webapp
  template:
    metadata:
      labels:
        app: flask-webapp
    spec:
      containers:
        - name: flask-webapp-pod
          image: kamranshaikh111/flask_webapp_kamran:v2
          ports:
            - containerPort: 8080
