apiVersion: v1
kind: Service
metadata:
  name: flask-webapp-ser
  labels:
    app: flask-webapp
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32767
      name: flask-webapp
  selector:
    app: flask-webapp
  type: NodePort
