apiVersion: v1
kind: Service
metadata:
  name: node-example
  labels:
    app: node-example
spec:
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32020
      name: node-example
  selector:
    app: node-example
  type: NodePort
