apiVersion: v1
kind: Service
metadata:
  name: cloudethix-clusterip
  namespace: deploy1
  labels:
    app: release_nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: release-nginx
  selector:
    app: release-nginx
