apiVersion: v1
kind: Pod
metadata:
  name: myapp-worker-1
  labels:
    node: worker-1
spec:
  containers:
  - name: my-container-1
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
